Main namelist debug
CICE-Consortium/CICE pull request #671
Opened 2021-12-02 18:49 UTC by daveh150

For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [ ] Short (1 sentence) summary of your PR: 
    Provide detailed output when namelist has wrong variables
- [ ] Developer(s): 
    David Hebert
- [ ] Suggest PR reviewers from list in the column to the right.
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
21 measured results of 21 total results
21 of 21 tests PASSED
0 of 21 tests PENDING
0 of 21 tests MISSING data
0 of 21 tests FAILED

- How much do the PR code changes differ from the unmodified code? 
    - [ x] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ x] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [x ] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ x] No 
- [ x] Please provide any additional information or relevant details below:
If you have a namelist variable incorrect (say CICE was updated with different namelist variable name), the error just tells you which namelist. This enhancement adds method to print the actual line in namelist. 

Example: CICE6 changed 'sst_data_type' to 'ocn_data_type'. If you didn't change it new code will now print:

 (abort_ice)ABORTED:
 (abort_ice) called from ice_init.F90
 (abort_ice) line number          579
 (abort_ice) error =
 (input_data)ERROR: reading namelist    sst_data_type   = 'gofs_daily'

2021-12-02 19:08 UTC, phil-blain commented
Hi David, I think this could be really useful. It's unfortunate that we have to repeat the code in several files, tough (but that would be a subject for another day!)

I noticed that the second commit is simply a fixup of the first one. You could use an [interactive rebase](https://git-rebase.io) to clean that up if you want.

I also noticed that you used a different email address for the two commits...

2021-12-02 19:23 UTC, apcraig commented
@daveh150.  This is a nice feature to have.  Knew we weren't handling this case well, but wasn't sure how to work around that.  Nice update.

2021-12-02 19:25 UTC, eclare108213 commented
I agree.  Does it make sense to pull all these bits of identical code into subroutine in CICE_Finalize (or somewhere)?

2021-12-02 19:27 UTC, daveh150 commented
Thank you Phillipe! I have one more update, I missed a namelist in cicecore/shared/ice_init_column.F90. Do I do an interactive rebase first, then push to my fork?

 

Thanks!

David

 

From: Philippe Blain ***@***.***> 
Sent: Thursday, December 2, 2021 13:09
To: CICE-Consortium/CICE ***@***.***>
Cc: David Hebert, Code 7322 ***@***.***>; Author ***@***.***>
Subject: Re: [CICE-Consortium/CICE] Main namelist debug (PR #671)

 

Hi David, I think this could be really useful. It's unfortunate that we have to repeat the code in several files, tough (but that would be a subject for another day!)

I noticed that the second commit is simply a fixup of the first one. You could use an interactive rebase <https://git-rebase.io>  to clean that up if you want.

I also noticed that you used a different email address for the two commits...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <https://github.com/CICE-Consortium/CICE/pull/671#issuecomment-984920483> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AE52VPDE3OMNLZOOO7SRFTTUO673BANCNFSM5JH3H6EQ> .
Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>  or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub> .

2021-12-02 19:28 UTC, phil-blain commented
Yes, though you would have to push with `--force` since you would be changing history.

2021-12-02 19:40 UTC, daveh150 commented
I pushed the commit to cicecore/shared/ice_init_column.F90. I also did the interactive rebase Phillipe suggested. I did not need to use --force, but it seemed to work. :-)

2021-12-02 19:48 UTC, apcraig requested changes
A few comments.  Since we're here, how about if we unify the implementation across different files to

         do while (nml_error > 0)
            read(nu_nml, nml=icefields_nml,iostat=nml_error)
            if (nml_error /= 0) exit
            ...
         end do

         if (nml_error /= 0) then
            backspace(nu_nml) 
            read(nu_nml,fmt='(A)') tmpstr2 
            call abort_ice(subname//'ERROR: reading namelist' // &
              trim(tmpstr2), &
              file=__FILE__, line=__LINE__)
         endif
         close(nu_nml)

2021-12-02 19:48 UTC, apcraig commented on cicecore/cicedynB/analysis/ice_history_drag.F90
> +         call abort_ice(subname//'ERROR: reading icefields_drag_nml' // &
Need a space at the end of the string like other calls.

2021-12-02 19:48 UTC, apcraig commented on cicecore/cicedynB/analysis/ice_history_fsd.F90
> +         call abort_ice(subname//'ERROR: reading icefields_fsd_nml'// &
need a space at the end of the ERROR string.

2021-12-02 19:48 UTC, apcraig commented on cicecore/cicedynB/analysis/ice_history_mechred.F90
> +         call abort_ice(subname//'ERROR: reading icefields_mechred_nml' // &
need a space at the end of the ERROR string.

2021-12-02 19:48 UTC, apcraig commented on cicecore/cicedynB/general/ice_init.F90
> +         call abort_ice(subname//'ERROR: reading namelist' // &
Need a space at the end of the ERROR string.

2021-12-02 19:50 UTC, apcraig commented
Sorry, an old comment got included in my review that wasn't supposed to be there.  I have removed it.

2021-12-02 21:17 UTC, daveh150 commented
I added the needed spaces and colon for output messages.

2021-12-06 18:55 UTC, apcraig approved these changes

2021-12-08 15:29 UTC, eclare108213 approved these changes

2021-12-08 18:35 UTC, merged