New 1d evp solver
CICE-Consortium/CICE pull request #895
Opened 2023-10-24 21:32 UTC by TillRasmussen

For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [ ] Short (1 sentence) summary of your PR: 
   Update of 1d evp solver
- [ ] Developer(s): 
    @TillRasmussen Jacob Poulsen, Intel, @mhrib 
- [ ] Suggest PR reviewers from list in the column to the right.
- [ ] @apcraig @eclare108213 
- [ ] Please copy the PR test results link or provide a summary of testing completed below.
  Pass all test except 1d as it has changed and jra55 forcing (not downloaded). This is true when 
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [x ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [ x] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [ ] Yes
    - [x ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [x ] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [ x] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [ ] No 
- [ ] Please provide any additional information or relevant details below:
QC test passed. See figures below
![ice_thickness_base](https://github.com/CICE-Consortium/CICE/assets/33480590/9de43255-bdcf-4919-8e60-a4923ee34582)
![ice_thickness_base_minus_evp1d](https://github.com/CICE-Consortium/CICE/assets/33480590/cb662c7a-dc10-48f4-81b1-5824456c17b6)
![ice_thickness_evp1d](https://github.com/CICE-Consortium/CICE/assets/33480590/4ee8f727-02d8-4f07-927d-4551076518e0)

Small updates may be foreseen. Change for CICE_Init is only changed for driver standalone. Despite this version matches the current evp implementation and therefore it should be included in the main branch. In addition documentation should be updated
A few original OMP statements has been commented out and marked with "TILL", The files affected by this are thiice_transport_remap.F90 and ice_diagnostics.F90

2023-10-26 23:37 UTC, eclare108213 approved these changes

2023-10-28 11:42 UTC, TillRasmussen commented
It is not necessary to update the documentation. I read through and it seems ok as there are no changes to namelist or principles

2023-10-30 18:55 UTC, apcraig commented
I've had a quick look at the PR.  I think if this is a "final" version, we should get it cleaned up a bit.  Why is the OMP commented out in ice_diagnostics?  I'm curious about the "pure" subroutine keyword.  I think the formatting in ice_dyn_evp1d.F90 needs to be cleaned up.  The indentation and subroutine separation is inconsistent.  I also think bench_v2c.F90 should be renamed.  I would like to test this on a few platforms before we merge just to make sure it's bit-for-bit and works properly.  Also, I think we should evaluate the performance of the evp1d a bit on typical resolutions.  We should have an idea of the configurations the evp1d might improve performance over the standard 2d evp implementation.  And maybe we should increase the test coverage a bit.

2023-10-30 18:59 UTC, apcraig commented
Does the current version of the 1d solver work with the C-grid.  If not, does the run abort?

2023-10-30 19:08 UTC, eclare108213 commented
Thanks @apcraig. I did approve this PR, and I think it could be merged soon, but I also want to make sure that everyone is okay with it.  Therefore I'll parse and prioritize these suggestions a bit.  

> Why is the OMP commented out in ice_diagnostics? 

Does commenting out the OMP lines change the answers, i.e. is there a bug in any of them?

> I'm curious about the "pure" subroutine keyword.

Me too.  I googled it, and it makes sense here.  If it helps the compiler to optimize the code, then I'm all for it.  Do we need to consider adding this in other places?  I don't think a change is needed for this PR, just more information for the future. 

> I think the formatting in ice_dyn_evp1d.F90 needs to be cleaned up. The indentation and subroutine separation is inconsistent.  I also think bench_v2c.F90 should be renamed. 

I agree.

> I would like to test this on a few platforms before we merge just to make sure it's bit-for-bit and works properly. 

Always a good idea.  But I think it's not going to be BFB in the tests that use 1D evp, right?  So the QC testing shown above should be sufficient to cover that.

> Also, I think we should evaluate the performance of the evp1d a bit on typical resolutions. We should have an idea of the configurations the evp1d might improve performance over the standard 2d evp implementation. And maybe we should increase the test coverage a bit.

I don't think documenting the performance improvements (or how to get them) is necessary in order to merge the PR, but I do agree that it's a good idea to document at some point.  It would be helpful to include this kind of information in the PR, if it is already available.

And @apcraig's last question about how this interacts with the C-grid is also a good one to ask!

2023-10-30 19:13 UTC, apcraig commented
With regard to testing, I understand evp1d and 2d evp are not bit-for-bit.  I just want to make sure the code changes are bit-for-bit with the prior version and that these code changes don't break anything.  I think it's worth testing on a few machines and compilers to make sure it's all robust.

2023-10-30 19:16 UTC, apcraig commented
Just a quick followup on testing.  Was regression testing done on freya?  Does the debug flag mean answers are changed with standard optimization for the 2d evp?  Or was the debug flag used just to prove the evp1d was bit-for-bit in that mode but that wasn't needed for the 2d evp?

2023-10-30 19:18 UTC, apcraig requested changes
See comments elsewhere.

2023-10-30 20:06 UTC, TillRasmussen commented
> With regard to testing, I understand evp1d and 2d evp are not bit-for-bit. I just want to make sure the code changes are bit-for-bit with the prior version and that these code changes don't break anything. I think it's worth testing on a few machines and compilers to make sure it's all robust.

I tested with Freya debug, Frey in previous normal mode and they were both bit for bit. Then I added the additional optimization where the compiler uses inline and other things (new version of Freya). Then it was not bit for bit.

2023-10-31 06:29 UTC, TillRasmussen commented
> Does the current version of the 1d solver work with the C-grid. If not, does the run abort?

No but this is not the case for the old implementation either

2023-10-31 06:30 UTC, TillRasmussen commented
> Just a quick followup on testing. Was regression testing done on freya? Does the debug flag mean answers are changed with standard optimization for the 2d evp? Or was the debug flag used just to prove the evp1d was bit-for-bit in that mode but that wasn't needed for the 2d evp?

I have not tested the 2d version

2023-10-31 08:34 UTC, mhrib commented
> > The indentation and subroutine separation is inconsistent. I also think bench_v2c.F90 should be renamed.
> I will fix the indentation. Any suggestion for benchv2c?

One of:
- ice_dyn_evp1d_core.F90
- ice_dyn_evp1d_core_v2c.F90

Or alternative simply inline it within ice_dyn_evp1d.F90

2023-10-31 16:32 UTC, apcraig commented
So, I'll make sure the 2d evp has not changed answers with this PR and that the evp1d runs fine on several platforms.  

The older 1d and the new 1d are bit-for-bit, is that right?  That's what you were testing mostly?

I understand 2d and 1d are not bit-for-bit unless optimization is reduced.  With higher optimization, QC tests pass 2d vs 1d.  That's the QC test above?

I leave it to others to decide whether bench_v2c should be inlined within ice_dyn_evp1d.F90.  I don't think that's necessary.  ice_dyn_evp1d_core.F90 seems fine.  Or maybe ice_dyn_evp1d_v2c.F90?  But I'm not sure what v2c means to be honest.

We should add an abort if the evp1d is chosen and grid_ice is "C or CD".  There is some logic in ice_init.F90 that checks dyn/grid_ice already,

```
      if (grid_ice == 'C' .or. grid_ice == 'CD') then
         if (kdyn > 1) then
            if (my_task == master_task) then
               write(nu_diag,*) subname//' ERROR: grid_ice = C | CD only supported with kdyn<=1 (evp or off)'
               write(nu_diag,*) subname//' ERROR: kdyn and grid_ice inconsistency'
            endif
            abort_list = trim(abort_list)//":46"
         endif
```

I suggest we just change that to something like

```
      if (grid_ice == 'C' .or. grid_ice == 'CD') then
         if (kdyn > 1 .or. (kdyn == 1 .and. evp_algorithm /= 'standard_2d')) then
            if (my_task == master_task) then
               write(nu_diag,*) subname//' ERROR: grid_ice = C | CD only supported with kdyn=1 and evp_algorithm=standard_2d'
               write(nu_diag,*) subname//' ERROR: kdyn and grid_ice inconsistency'
            endif
            abort_list = trim(abort_list)//":46"
         endif
```

2023-10-31 16:47 UTC, TillRasmussen commented
> So, I'll make sure the 2d evp has not changed answers with this PR and that the evp1d runs fine on several platforms.
> 
> The older 1d and the new 1d are bit-for-bit, is that right? That's what you were testing mostly?
> 
> I understand 2d and 1d are not bit-for-bit unless optimization is reduced. With higher optimization, QC tests pass 2d vs 1d. That's the QC test above?
> 
> I leave it to others to decide whether bench_v2c should be inlined within ice_dyn_evp1d.F90. I don't think that's necessary. ice_dyn_evp1d_core.F90 seems fine. Or maybe ice_dyn_evp1d_v2c.F90? But I'm not sure what v2c means to be honest.
> 
> We should add an abort if the evp1d is chosen and grid_ice is "C or CD". There is some logic in ice_init.F90 that checks dyn/grid_ice already,
> 
> ```
>       if (grid_ice == 'C' .or. grid_ice == 'CD') then
>          if (kdyn > 1) then
>             if (my_task == master_task) then
>                write(nu_diag,*) subname//' ERROR: grid_ice = C | CD only supported with kdyn<=1 (evp or off)'
>                write(nu_diag,*) subname//' ERROR: kdyn and grid_ice inconsistency'
>             endif
>             abort_list = trim(abort_list)//":46"
>          endif
> ```
> 
> I suggest we just change that to something like
> 
> ```
>       if (grid_ice == 'C' .or. grid_ice == 'CD') then
>          if (kdyn > 1 .or. (kdyn == 1 .and. evp_algorithm /= 'standard_2d')) then
>             if (my_task == master_task) then
>                write(nu_diag,*) subname//' ERROR: grid_ice = C | CD only supported with kdyn=1 and evp_algorithm=standard_2d'
>                write(nu_diag,*) subname//' ERROR: kdyn and grid_ice inconsistency'
>             endif
>             abort_list = trim(abort_list)//":46"
>          endif
> ```

v2c refers to benchmark or standalone test. There were test v0 (2d), v1 (1d) and v2a, v2b, v2c, v2d, v2e. Each of the v2? cases had their own omp implementation.

I have updated the code with the changes that were requested (locally).
I want to see that the test pass before I add a commit.

I run the test now but I will not complete before tomorrow.
I am testing:
 old 2d vs new 2d (with debug)
new 2d vs new 1d (with debug)

And then additionally the qc test without debug

Thus I have not really tested the old 1d vs the new as the structure of the dynamical core has changed quite a bit with inclusions of sub functions in the stress function.

I can add the same test without debug.

I have added check for evp_algorithm and tripolar for the 1d solver in cice init. This will abort. 
I can include the checks for kdyn as well. 
both ice_dyn_evp1d and bench (now ice_dyn_core1d) have been styled (I hope)

2023-10-31 17:42 UTC, apcraig commented
I would do the old 2d vs new 2d without debug.  There are several tests that turn on debugging by default so you can usually see when optimization make things not bit-for-bit.  But the 2d should not have changed answers with full optimization, right?   We want to confirm that.  I'll do the same to confirm independently once the newest changes are pushed.

2023-10-31 18:13 UTC, TillRasmussen commented
I will make the test both with and without debug. I added check for c/cd
grid and eap/VP

Till

tir. 31. okt. 2023 18.42 skrev Tony Craig ***@***.***>:

> I would do the old 2d vs new 2d without debug. There are several tests
> that turn on debugging by default so you can usually see when optimization
> make things not bit-for-bit. But the 2d should not have changed answers
> with full optimization, right? We want to confirm that. I'll do the same to
> confirm independently once the newest changes are pushed.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CICE-Consortium/CICE/pull/895#issuecomment-1787688131>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH7N7DTEXVFJY7JSMKD7PA3YCE2BTAVCNFSM6AAAAAA6OK6NFWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBXGY4DQMJTGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-31 21:46 UTC, apcraig commented
Also, I understand the v2c now.  If you want to carry that string around, I think ice_dyn_evp1d_corev2c.F90 or ice_dyn_evp1d_benchv2c.F90 or ice_dyn_evp1d_v2c.F90 would be OK too.

2023-11-01 13:15 UTC, TillRasmussen commented
In addition to the commit statement the driver for DMI has been updated.
Following test has been created/updated
Debug mode
Old vs new - bit for bit except when  1d cases are compared
new 2d vs new 1d bit for bit
Without debug
Old 2d vs new 2d. Gnu compiler is bit for bit but Intel is not on some cases varying block sizes and. Note that I only changed level of optimization within Macro_intel_freya not on Marcro_gnu_freya. I will do an additonal test to check whether this is the issue
new 1d vs new 2d; more differences than 2d vs 2d

I did not rerun the qc test. Should I ?

2023-11-01 15:29 UTC, TillRasmussen commented
I tested the old code with the old and the new versions of Macro for Intel compilation and that was the cause for the none bit for bit cases  or at least it is none bit for bit in the excact same test.

2023-11-01 16:18 UTC, apcraig commented
Another comment, if you want to add the code updates to other drivers, I think that's OK.  I know you can't test.  I don't think we've decide how to handle this best.  Is it better to add the code and then for the chance the code will break or to not add the code and for the group using the driver to be unaware it could/should be added?

2023-11-01 16:36 UTC, apcraig commented
The checks/aborts were added in CICE_InitMod.F90 in the standalone CICE and the DMI driver.  That's not where they belong.  Those changes should be removed again.  You want to add it to ice_init.F90 so it's trapped when the namelist is read (not later) and so it's done for all drivers.  See the code suggestion above.  If we also need to add an abort for evp1d and tripole, then it should also be added in that same section.

2023-11-01 16:43 UTC, apcraig commented
I'm still curious about the "pure" subroutine label.  I don't know much about this keyword, but it seems to have some implications.  If I understand correctly, it provides the compiler information about the subroutine, namely that all calculations are acted only on local data (or something like that).  But it implicitly means we should never add debug statements to those subroutines, or timers, or any other global data manipulation.  Again, I may not understand all the details.  Is the use of pure necessary?  If so, why?  If it's not necessary, does it improve performance?  How much?  My preference would be to NOT use pure unless it provides some benefit.

2023-11-01 19:03 UTC, eclare108213 commented
Your QC test was without debugging on, but what was it comparing?  Old/new 1d/2d?  There are several combinations there.  I think the two important cases for our purposes are (1) old vs new 2d and (2) whatever you did with 1d above.

> Another comment, if you want to add the code updates to other drivers, I think that's OK. I know you can't test. I don't think we've decide how to handle this best. Is it better to add the code and then for the chance the code will break or to not add the code and for the group using the driver to be unaware it could/should be added?

Our decision was that we (the Consortium) would rely on the modeling centers to keep their own drivers up to date -- we aren't responsible for things in them that don't work because we can't test them.  That said, I do think it's a good idea to make an attempt to implement the critical changes that would be needed, if only to alert the centers that they need attention.

2023-11-01 19:26 UTC, TillRasmussen commented
> I'm still curious about the "pure" subroutine label. I don't know much about this keyword, but it seems to have some implications. If I understand correctly, it provides the compiler information about the subroutine, namely that all calculations are acted only on local data (or something like that). But it implicitly means we should never add debug statements to those subroutines, or timers, or any other global data manipulation. Again, I may not understand all the details. Is the use of pure necessary? If so, why? If it's not necessary, does it improve performance? How much? My preference would be to NOT use pure unless it provides some benefit.

Translation (ish) from Jacob: pure is not necessary for the compiler, however it ensures that they are written in a nice way and for instance they do not change module variables. This means that pure is a way of showing that a function behaves well and is tested. Therefore it is not possible to do debug with this. What one would do when testing would be to remove it and then put it back in when done.

I will remove it

2023-11-01 19:47 UTC, TillRasmussen commented
> The checks/aborts were added in CICE_InitMod.F90 in the standalone CICE and the DMI driver. That's not where they belong. Those changes should be removed again. You want to add it to ice_init.F90 so it's trapped when the namelist is read (not later) and so it's done for all drivers. See the code suggestion above. If we also need to add an abort for evp1d and tripole, then it should also be added in that same section.

The suggestion above covers parts of this. The will also be issues with for instance b grid.
Is there a guideline for how the numbers are selected? It is 46 for the c and cd clause

2023-11-01 20:07 UTC, apcraig commented
The error numbers are arbitrary.  But the idea is that different errors will have different error codes.  So they should generally be unique.  The error codes exist so CICE can go thru all the input and detect all the problems.  We don't want each error to abort, we want to check all the inputs once and throw multiple errors codes if needed.

I think you could use the "46" block to detect all inconsistencies between grid_ice and dynamics settings.  Maybe just write different strings for different errors but if any are triggered, it's error "46".  Let me know if you need help.

2023-11-01 22:21 UTC, TillRasmussen commented
I removed all from CICE_Init. abort checks to the suggested place and ice_dyn_evp1d_init to evp_init. 
I think that was what was requested except for the qc test updates.
I did not remove pure (forgot before starting the test), however this is a small thing.

2023-11-02 17:27 UTC, apcraig commented
Sorry, several other things as I look closer.

If you could remove "pure", that would be great.

Also looking at the ice_dyn_evp1d code.  You have a routine there called "function io_new_unit".  That should be removed and you should use "get_fileunit" which is in module ice_fileunits.

Also, you have "evp_1d_nml_reader".  I don't think that implementation is consistent with the rest of the namelist readers in CICE.  I have many questions
- why are you reading from a different file?  I think that namelist group should be in "ice_in"?
- I think you need to read into master and broadcast, you can see how other namelist groups handle this.  I encourage you to use similar style for consistency.

Some the output in ice_dyn_evp1d is of the form
    if (ierr/=0) stop 'Error allocating stress'
or
    write(*,'(a21)') 'Close evp 1d log'
- Everything should be written to nu_diag
- There are places where all tasks write output like dyn_evp1d_finalize and evp_1d_nml_reader, that should be fixed to be just master_task.
- The "stops" should be using abort_ice
    if (ierr/=0) then
       call abort_ice(subname//' ERROR: allocating stress', file=__FILE__, line=__LINE__)
    endif

subname should be defined in all new subroutines and functions.

2023-11-02 17:35 UTC, apcraig commented
Also, the thing that's being read in the evp1d namelist, "buf1d", is not well defined or named.  It's module data, but I have no idea what it is.  Could it have a better name?  Is it required?  It should be defined clearly somewhere in the file and  the documentation needs to be updated to reflect this new namelist group and namelist input.

2023-11-02 20:59 UTC, TillRasmussen commented
> Sorry, several other things as I look closer.
> 
> If you could remove "pure", that would be great.
>

Pure is removed 
> Also looking at the ice_dyn_evp1d code. You have a routine there called "function io_new_unit". That should be removed and you should use "get_fileunit" which is in module ice_fileunits.
>

This was only used when reading namelist, which was only used to readin buf1d. buf1d is also removed. The namelist mentioned below only readin buf1d. The reader has also been removed as buf1d is removed. 
  
> Also, you have "evp_1d_nml_reader". I don't think that implementation is consistent with the rest of the namelist readers in CICE. I have many questions
> 
>     * why are you reading from a different file?  I think that namelist group should be in "ice_in"?
> 

Removed

>     * I think you need to read into master and broadcast, you can see how other namelist groups handle this.  I encourage you to use similar style for consistency.
> 
> 
> Some the output in ice_dyn_evp1d is of the form if (ierr/=0) stop 'Error allocating stress' or write(*,'(a21)') 'Close evp 1d log'
> 
>     * Everything should be written to nu_diag
> 
>     * There are places where all tasks write output like dyn_evp1d_finalize and evp_1d_nml_reader, that should be fixed to be just master_task.
> 
>     * The "stops" should be using abort_ice
>       if (ierr/=0) then
>       call abort_ice(subname//' ERROR: allocating stress', file=**FILE**, line=**LINE**)
>       endif
> 
> 
ok

> subname should be defined in all new subroutines and functions.

Ok

2023-11-02 21:02 UTC, TillRasmussen commented
> Also, the thing that's being read in the evp1d namelist, "buf1d", is not well defined or named. It's module data, but I have no idea what it is. Could it have a better name? Is it required? It should be defined clearly somewhere in the file and the documentation needs to be updated to reflect this new namelist group and namelist input.

In the original all 1d variables were allocated and deallocated at every time step. We have experiemented a bit with this and how to do this more efficient. buf1d was a legacy from this. It has been removed for now. But may be introduced again.

2023-11-03 17:30 UTC, apcraig commented
I've pulled the latest changes into a sandbox.  Will start some initial testing.  A few suggestions
- dyn_evp1d_finalize, fix the write statement
- add subname to ice_dyn_core1d subroutines
- remove pure from subroutine strain_rates in ice_dyn_core1d.F90
- rename subroutines in ice_dyn_core1d so they are unique (stress, stepu, strain_rates -> stress1d, step1d, strain_rates_1d?)
- add icepack abort check after "call icepack_query_parameters" in ice_dyn_core1d.F90:stepu.  That is
```
      call icepack_warnings_flush(nu_diag)
      if (icepack_warnings_aborted()) call abort_ice(error_message=subname, &
         file=__FILE__, line=__LINE__)
```
- "end subroutine evp1d_alloc_static_na" needs to be indented 
- please change subname in ice_dyn_evp.F90:init_evp to "init_evp"

2023-11-03 17:35 UTC, TillRasmussen commented
Will do.

I have not tested the updates from last night  more than they don't crash
and they seem to run in debug mode. I haven't had the time today to do more.

fre. 3. nov. 2023 18.30 skrev Tony Craig ***@***.***>:

> I've pulled the latest changes into a sandbox. Will start some initial
> testing. A few suggestions
>
>    - dyn_evp1d_finalize, fix the write statement
>    - add subname to ice_dyn_core1d subroutines
>    - remove pure from subroutine strain_rates in ice_dyn_core1d.F90
>    - rename subroutines in ice_dyn_core1d so they are unique (stress,
>    stepu, strain_rates -> stress1d, step1d, strain_rates_1d?)
>    - add icepack abort check after "call icepack_query_parameters" in
>    ice_dyn_core1d.F90:stepu. That is
>
>       call icepack_warnings_flush(nu_diag)
>       if (icepack_warnings_aborted()) call abort_ice(error_message=subname, &
>          file=__FILE__, line=__LINE__)
>
>
>    - "end subroutine evp1d_alloc_static_na" needs to be indented
>    - please change subname in ice_dyn_evp.F90:init_evp to "init_evp"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CICE-Consortium/CICE/pull/895#issuecomment-1792856012>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH7N7DRSFL4SUBK5JFGXYTTYCUS3FAVCNFSM6AAAAAA6OK6NFWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJSHA2TMMBRGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-03 17:43 UTC, apcraig commented
Thanks @TillRasmussen.  No problem.  I'll do some initial testing, you can test too.  As we finalize the code, I'll ramp up my testing.  I think the changes being made are largely formatting, none of these changes should be consequential.   Keep me posted, will do the same.

2023-11-03 19:38 UTC, apcraig commented
One other thing if you don't mind (not related to evp1d).  Could you add the icepack warning/abort calls in subroutine seabed_stress_factor_prob in ice_dyn_shared.F90.  There can be one set of warning/abort calls after the 4 existing calls or it could be changed to this,

```
      call icepack_query_parameters(rhow_out=rhow, rhoi_out=rhoi, &
           gravit_out=gravit, pi_out=pi, puny_out=puny)
      call icepack_warnings_flush(nu_diag)
      if (icepack_warnings_aborted()) call abort_ice(error_message=subname, &
         file=__FILE__, line=__LINE__)
```
Thanks.

2023-11-03 20:04 UTC, apcraig commented
Ran a full test suite on cheyenne intel.  Everything is bit-for-bit with current Consortium main except tests with evp1d turned on.  This is a good result and expected.  Will test other compilers when code is further updated.

2023-11-03 23:34 UTC, TillRasmussen commented
@apcraig I have added most of your suggestion without testing. One thing though. I don't think that  I want rhow to be queried  within stepu at every timestep as it includes an if statement. It is not defined as a constant and it appears to me that there are some couplers who varies this at every timestep. My question is should this be updated at every time step or once per run?

2023-11-03 23:51 UTC, apcraig commented
> @apcraig I have added most of your suggestion without testing. One thing though. I don't think that I want rhow to be queried within stepu at every timestep as it includes an if statement. It is not defined as a parameter in icepack and it appears to me that there are some couplers who varies this at every timestep. This is based on a "grep" command. My question is should this be updated at every time step or once per run?

I'm not the best person to ask, it's certainly possible that rhow is changing at each timestep and gridcell, but that's not really how the icepack parameters are supposed to work.  If rhow does vary over the run, maybe it should be a subroutine argument rather than something that is set via icepack_parameters.  @eclare108213 @dabail10?

2023-11-04 00:00 UTC, apcraig commented
I ran some timing tests with the evp2d vs evp1d.  Results are here, https://docs.google.com/spreadsheets/d/1JDaPc0pDlngsYuIN2dF2DzCgTSV7zER9HYgw_kPb9pY/edit?usp=sharing

There are 3 tables.  The most interesting is table A.  This should be where evp1d excels and it does beat evp2d at 1 thread.  But why does the cost go up so much at 2 threads relative to 1 thread?  Then it scales again, but that multi-thread penalty is huge.  Table B is not a good test for evp1d (single threaded), but it does show a large penalty when shifting from one node to two nodes.  Are both of these issues the same thing, cost of gather/scatter in evp1d?  Do you want me to look at the timing in more detail and the implementation of the gather/scatter?

2023-11-04 00:51 UTC, TillRasmussen commented
> The

Are the timings the "timer_evp_2d"?

Within the implementation in CICE I have been very focused on the correctness rather than the performance and I think that it is more robust now than the old version. From the test so far it seems to me that if I had not changed the Macro_intel_freya within this pull request then it would have been bit for bit both with and without debug flags. This was not the case before.

You are right that it is a large penalty (table a) and it should be investigated  where this originates from. 
I have not done the analysis for that part.

My first thought is that there could be something in the compiler flags.
The size of the domain may also be an issue. Larger domain and more evp iterations should improve the 1d solvers efficiency.
Bottom line. Timers should be added to see where the bottleneck is.
For the scatter/gather part then the next step is to go directly from 3d (i,j,iblk) to 1d instead of creating the global arrays. We should at least discuss the approach before starting to work on it. I know that Jacob has some intentions but he is only partly available for the time being.

That being said I would like that to be in the next pull request as this version 1d seems to be more correct than the one currently implemented.

2023-11-04 08:57 UTC, TillRasmussen commented
Again in the next comment. Is it really necessary gather/scatter all the stress terms? It needs to be done when restart are read by they don't change in between. That is already 12 communication calls per time step. In addition it is used to write restart.

2023-11-04 18:29 UTC, apcraig commented
The timings are the "Dynamics" timer.  

I'm fine evaluating and fixing the performance in a future commit.  I agree we should continue to move forward with this update.

2023-11-05 14:26 UTC, TillRasmussen commented
Updated. inclusion of timer evp_1d is included.
New and old 2d is bit for bit.

2023-11-06 16:16 UTC, eclare108213 reviewed
What is the status of this PR?  Following up on some of the comments above:

In the initial PR description, what were the 2 runs that were compared for the QC test?  Were they before-and-after evp1D runs, or comparing this new evp1D with the current 2D?

Did you figure out why OMP in ice_diagnostics.F90 was crashing your runs?  
What’s going on with OMP in the remapping module?

Regarding performance - 
Should we note in the documentation that evp1D does not necessarily improve performance over the 2D discretization because of MPI calls?  It is designed to improve performance when the entire dynamics calculation is moved onto a single processor (or GPU), but this capability has not yet been implemented in CICE’s build scripts, right?  Maybe that’s worth a note.

Till asked:  Is it really necessary gather/scatter all the stress terms? 
@dabail10 can weigh in here, but I think that is because of the tripole meshes.  We've never gotten the halo calculations to work all the time for every grid, so we ended up just doing the gather/scatters.  I'd prefer to only do that on grids where it's necessary, but that probably involves ifdefs or more if blocks, and it is prone to errors.  Open to ideas.

2023-11-06 17:21 UTC, TillRasmussen commented
@eclare108213 I think that status is that I have implemented what is needed based on Tony's comments and that it  is close be in place. If not then please remind me :). I ran a couple of diffferent qc test, but I have not have not seen the result (I need a better wifi). debug runs are bit for bit, none debug runs are not..

In terms of performance then that will have to be investigated more, however Tony's spread sheet indicated that there are things to be improved.

The reason I mentioned stress arrays is that this contains 12 fields which are gathered at every time step. They are only changed in the stress routine. In between time steps there would be some logic in handling active t points that are no longer active (value set to 0) or vice versa.  If I am missing something here let me know. If my assumption is correct then we only need to gather at the first time step and scatter the values when they are needed for I/O.

2023-11-06 17:30 UTC, apcraig commented on cicecore/cicedyn/dynamics/ice_dyn_shared.F90
> +         file=__FILE__, line=__LINE__)
I agree, that's why I had proposed in my review.  Either 1 flush/check after the 4 query calls or 1 query call for all 4 parameters and then the flush/check call.

2023-11-06 17:47 UTC, apcraig commented
This is looking pretty good.  A couple things (sorry, partly I keep seeing new things to fix, I do think we are close)

- see inline comments at ice_dyn_shared.F90, line 1457
- see inline comment at ice_init.F90 line 1316
- I think timer_evp_1d should INCLUDE the gather/scatter parts.  In fact, I think timer_evp_1d should be moved back out to ice_dyn_evp.F90 so it's co-located with timer_evp_2d so it's clearer what is being timed.   I understand that there may be interest in timing just the 1d kernel, but I think timer_evp_2d and timer_evp_1d should be fundamentally timing the same thing.  There could be additional timers added to time various parts of the implementation, but those should be just for debugging.  In fact, there could be just one timer, timer_evp that would surround the 1d and 2d calls.
- In module ice_dyn_core1d, could you add implicit none to the module and subroutines, declare everything private and then make the public interfaces/data explicit.  I understand all interfaces are public in this routine, but it makes the code clearer and meets the coding standard of the rest of the model.  implicit none is important.  Also check other evp1d routines, make sure implicit none is declared in all modules and subroutines.

2023-11-06 20:32 UTC, dabail10 commented
> > @apcraig I have added most of your suggestion without testing. One thing though. I don't think that I want rhow to be queried within stepu at every timestep as it includes an if statement. It is not defined as a parameter in icepack and it appears to me that there are some couplers who varies this at every timestep. This is based on a "grep" command. My question is should this be updated at every time step or once per run?
> 
> I'm not the best person to ask, it's certainly possible that rhow is changing at each timestep and gridcell, but that's not really how the icepack parameters are supposed to work. If rhow does vary over the run, maybe it should be a subroutine argument rather than something that is set via icepack_parameters. @eclare108213 @dabail10?

rhow is indeed a constant. So, the query_parameters should be outside the dynamics loop.

2023-11-06 20:36 UTC, dabail10 commented
> What is the status of this PR? Following up on some of the comments above:
> 
> In the initial PR description, what were the 2 runs that were compared for the QC test? Were they before-and-after evp1D runs, or comparing this new evp1D with the current 2D?
> 
> Did you figure out why OMP in ice_diagnostics.F90 was crashing your runs? What’s going on with OMP in the remapping module?
> 
> Regarding performance - Should we note in the documentation that evp1D does not necessarily improve performance over the 2D discretization because of MPI calls? It is designed to improve performance when the entire dynamics calculation is moved onto a single processor (or GPU), but this capability has not yet been implemented in CICE’s build scripts, right? Maybe that’s worth a note.
> 
> Till asked: Is it really necessary gather/scatter all the stress terms? @dabail10 can weigh in here, but I think that is because of the tripole meshes. We've never gotten the halo calculations to work all the time for every grid, so we ended up just doing the gather/scatters. I'd prefer to only do that on grids where it's necessary, but that probably involves ifdefs or more if blocks, and it is prone to errors. Open to ideas.

In the regular dynamics, we do halo updates. We have special halo updates for the tripole grids. We don't do gather / scatters. I don't understand why the gather / scatter calls are required in the 1D EVP?

2023-11-06 22:03 UTC, TillRasmussen commented
> > What is the status of this PR? Following up on some of the comments above:
> > In the initial PR description, what were the 2 runs that were compared for the QC test? Were they before-and-after evp1D runs, or comparing this new evp1D with the current 2D?
> > Did you figure out why OMP in ice_diagnostics.F90 was crashing your runs? What’s going on with OMP in the remapping module?
> > Regarding performance - Should we note in the documentation that evp1D does not necessarily improve performance over the 2D discretization because of MPI calls? It is designed to improve performance when the entire dynamics calculation is moved onto a single processor (or GPU), but this capability has not yet been implemented in CICE’s build scripts, right? Maybe that’s worth a note.
> > Till asked: Is it really necessary gather/scatter all the stress terms? @dabail10 can weigh in here, but I think that is because of the tripole meshes. We've never gotten the halo calculations to work all the time for every grid, so we ended up just doing the gather/scatters. I'd prefer to only do that on grids where it's necessary, but that probably involves ifdefs or more if blocks, and it is prone to errors. Open to ideas.
> 
> In the regular dynamics, we do halo updates. We have special halo updates for the tripole grids. We don't do gather / scatters. I don't understand why the gather / scatter calls are required in the 1D EVP?

CICE is in general in 2d also for the 1d solver. This means that for instance uvel and vvel are expected to be of the form uvel(i,j,iblck) in the rest of the code. Ideally this was not the case and gather scatter was not needed. 

The 2d version works on blocks and therefore it needs to do halo swap.
The 1d version works on the global domain. Therefore it does not need halo swap, however it updates the boundary when cyclic boundaries are present, which is a much simpler process.
For now there are too many gather scatter calls as both stress and velocities are only modified in the sub cycling iteration. Therefore it is only necessary to gather  these at time step one of each run and to scatter when either history or restart files are created. This requires some "index magic". Therefore I would really like to have this in a follow up push.

On the rhow. It is not set to be a parameter in icepack_parameters. If this should not be a constant then I suppose that it should originate from the coupler and be  a function t and s.

2023-11-06 22:16 UTC, TillRasmussen commented
I have changed the requested parts ecept for one part if
@apcraig when you refer to inline then it is what @eclare108213 suggested.

The exception is the timers. If I move timer_evp_1d outside of the gather/scatter then I should get the same result as I would get for timer_evp_2d when running with 1d solver

2023-11-06 23:01 UTC, apcraig commented
> I have changed the requested parts ecept for one part if @apcraig when you refer to inline then it is what @eclare108213 suggested.
> 
> The exception is the timers. If I move timer_evp_1d outside of the gather/scatter then I should get the same result as I would get for timer_evp_2d when running with 1d solver

I think that's my point, we should compare apples and apples.  timer_evp whether 1d or 2d times the same operation, one with the 1d solver, the other with the 2d solver.  I don't think it makes sense to just time the 1d core excluding the overhead to switch between 2d and 1d.  That is part of the cost of the 1d solver, yes?  And that total cost should be compared to the equivalent 2d solver cost.  We could have both I suppose.  I would define timer_evp_1d to be the whole cost including 2d->1d->2d operations.  Then I would have another time, say timer_evp_1dcore and that could be just the evp1d core.  The point is that if users compare timer_evp_1d and timer_evp_2d, that's not going to be a meaningful comparison in terms of deciding with version of evp to use if you're timing is inconsistent.

2023-11-06 23:14 UTC, TillRasmussen commented
A suggestion
rename timer_evp_2d to timer_evp or timer_evp_iter 

rename timer_evp_1d to timer_evp1d_core

2023-11-06 23:16 UTC, apcraig commented
Also, strain_rates_1d and calc_diag_1d still needs implicit none.

2023-11-06 23:22 UTC, apcraig commented
> A suggestion rename timer_evp_2d to timer_evp or timer_evp_iter
> 
> rename timer_evp_1d to timer_evp1d_core

That was also one of my suggestions.  You can just rename timer_evp_2d to timer_evp and move it outside the evp1d/2d code.   OK, looking at the code now, it already is outside the evp1d/2d code.  I assumed timer_evp_2d was timing the 2d code and timer_evp_1d was timing the 1d code.  But that is not the case, timer_evp_2d was timing the evp code and timer_evp_1d is timing the evp1d core.  That's confusing, I'm glad we're fixing that.  I agree, rename timer_evp_2d to timer_evp and then rename timer_evp_1d to something like timer_evp1d_core.  Thanks.

2023-11-06 23:38 UTC, TillRasmussen commented
> Also, strain_rates_1d and calc_diag_1d still needs implicit none.

The other modules only have implicit none in the module declaration and not in the subroutine. See e.g. ice_dyn_shared and ice_dyn_evp

2023-11-06 23:40 UTC, apcraig commented
> > Also, strain_rates_1d and calc_diag_1d still needs implicit none.
> 
> The other modules only have implicit none in the module declaration and not in the subroutine. See e.g. ice_dyn_shared and ice_dyn_evp

You're right.  Thanks for checking and reminding me.

2023-11-07 17:27 UTC, apcraig commented
I'm starting some more extensive testing.  The gnu compiler is failing with debug flags on.  It complains about x, y, lvecx, lvecy declarations in setdiff in ice_dyn_evp1d.F90.  It says lvecx is not declared before being used in x(1:lvecx).  The pgi and intel compiler don't seem to be bothered.  Anyway, the following change is needed,

```
-     integer(kind=int_kind), intent(in) :: x(1:lvecx), y(1:lvecy), lvecx,lvecy
+     integer(kind=int_kind), intent(in) :: lvecx, lvecy
+     integer(kind=int_kind), intent(in) :: x(1:lvecx), y(1:lvecy)

```
Please update and then I'll continue testing.  Thanks.

2023-11-07 17:43 UTC, TillRasmussen commented
> I'm starting some more extensive testing. The gnu compiler is failing with debug flags on. It complains about x, y, lvecx, lvecy declarations in setdiff in ice_dyn_evp1d.F90. It says lvecx is not declared before being used in x(1:lvecx). The pgi and intel compiler don't seem to be bothered. Anyway, the following change is needed,
> 
> ```
> -     integer(kind=int_kind), intent(in) :: x(1:lvecx), y(1:lvecy), lvecx,lvecy
> +     integer(kind=int_kind), intent(in) :: lvecx, lvecy
> +     integer(kind=int_kind), intent(in) :: x(1:lvecx), y(1:lvecy)
> ```
> 
> Please update and then I'll continue testing. Thanks.

added

2023-11-08 04:41 UTC, apcraig commented
OK, ran full tests suites and a couple issues arise.  First, the easy one.  These tests should be removed from the test suites (omp_suite.ts) because evp1d with gridC or gridCD aborts now, so the tests will always fail, as they should.

```
smoke          gx3     4x4        alt04,reprosum,run10day,gridc
smoke          gx3     4x4        alt04,reprosum,run10day,gridcd
smoke          gx3     8x1        alt04,reprosum,run10day,cmplogrest,thread,gridc       smoke_gx3_4x4_alt04_gridc_reprosum_run10day
smoke          gx3     8x1        alt04,reprosum,run10day,cmplogrest,thread,gridcd       smoke_gx3_4x4_alt04_gridcd_reprosum_run10day
```

I wouldn't ask for that change but another one has to be made.  The evp1d fails in several compilers when the debug flags are on,

```
forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable G_HTE when it is not allocated

Image              PC                Routine            Line        Source             
cice               00000000023BC37F  Unknown               Unknown  Unknown
cice               000000000082F0C3  ice_dyn_evp_mp_in         137  ice_dyn_evp.F90
cice               0000000000408DAE  cice_initmod_mp_c         136  CICE_InitMod.F90
```

I checked the code, the problem is that the call to dyn_evp1d_init is called on all tasks, but G_HTE and G_HTN are only allocated on the master_task.  They are also only used on master_task in the subroutine, so without debug, things run fine.  It's not really a problem that G_HTE and G_HTN are not declared on other tasks except for the debug checks.  Looking at the code, the problem is in the variable pgl_global_ext.  That variable is initialized to false, broadcast to all tasks, then updated ONLY on the root task after that when evp1d is on.  So master_task has pgl_global_ext set to true but other tasks have it set to false.  This is a problem so those arrays are only allocated on master_task.

Looking at the "pgl" implementation leaves me with lots of questions.
- why does the loglcal, pgl_global_ext, even exists, it's true only when evp_algorithm='shared_mem_1d'.  Why aren't we just using that check and get rid of pgl_global_ext.  
- there is a subroutine in ice_boundary called "primary_grid_lengths_global_ext".  That subroutine has no MPI in it, it should not be in ice_boundary (the mpi and serial version are identical).  That subroutine should probably be in ice_grid.F90.  That also keeps the "pgl" stuff more local.
- G_HTE and G_HTN only need to be defined on the master_task and they are global arrays and persistent.  But they are only needed for the evp1d initialization.
  - Why can't G_HTE and G_HTN be allocated and initialized in dyn_evp1d_init like G_dxT, G_dyT, G_uarear, and G_tmask?
  - Why aren't all these global arrays deallocated at the end of dyn_evp1d_init?  Maybe the subroutine does it automatically, but I don't think we can count on it and it would be better to be explicit.

Anyway, I think you should consider the following implementation
- get rid of pgl_global_ext
- move G_HTE and G_HTN into dyn_evp1d_init (like G_dxT, G_dyT, G_uarear, and G_tmask) as local variables.  Those would be computed by gathering HTE and HTN then calling primary_grid_lengths_global_ext (which now lives in ice_dyn_evp1d).  Or could G_HTE and G_HTN be added to "global_static" and initialized with a call to gather_global_ext?  That would be even better!  That would get rid of primary_grid_lengths_global_ext completely.
- deallocate all those global arrays at the end of dyn_evp1d_init (if you're clever, you can allocate those arrays to size "1" on non root tasks if you want.  they have to be allocated temporarily, but they are never used).

That would clean up the implementation quite a bit (get rid of pgl_global_ext, localize all logic associated with G_HTE and G_HTN to dyn_evp1d_init, maybe get rid of primary_grid_lengths_global_ext, and reduce memory overall) and should fix the current problem.  Hopefully that makes sense, maybe I'm missing something.  If you want some help, let me know.

2023-11-08 08:39 UTC, TillRasmussen commented
> OK, ran full tests suites and a couple issues arise. First, the easy one. These tests should be removed from the test suites (omp_suite.ts) because evp1d with gridC or gridCD aborts now, so the tests will always fail, as they should.
> 
> ```
> smoke          gx3     4x4        alt04,reprosum,run10day,gridc
> smoke          gx3     4x4        alt04,reprosum,run10day,gridcd
> smoke          gx3     8x1        alt04,reprosum,run10day,cmplogrest,thread,gridc       smoke_gx3_4x4_alt04_gridc_reprosum_run10day
> smoke          gx3     8x1        alt04,reprosum,run10day,cmplogrest,thread,gridcd       smoke_gx3_4x4_alt04_gridcd_reprosum_run10day
> ```
> 
> I wouldn't ask for that change but another one has to be made. The evp1d fails in several compilers when the debug flags are on,
> 
> ```
> forrtl: severe (408): fort: (8): Attempt to fetch from allocatable variable G_HTE when it is not allocated
> 
> Image              PC                Routine            Line        Source             
> cice               00000000023BC37F  Unknown               Unknown  Unknown
> cice               000000000082F0C3  ice_dyn_evp_mp_in         137  ice_dyn_evp.F90
> cice               0000000000408DAE  cice_initmod_mp_c         136  CICE_InitMod.F90
> ```
> 
> I checked the code, the problem is that the call to dyn_evp1d_init is called on all tasks, but G_HTE and G_HTN are only allocated on the master_task. They are also only used on master_task in the subroutine, so without debug, things run fine. It's not really a problem that G_HTE and G_HTN are not declared on other tasks except for the debug checks. Looking at the code, the problem is in the variable pgl_global_ext. That variable is initialized to false, broadcast to all tasks, then updated ONLY on the root task after that when evp1d is on. So master_task has pgl_global_ext set to true but other tasks have it set to false. This is a problem so those arrays are only allocated on master_task.
> 
> Looking at the "pgl" implementation leaves me with lots of questions.
> 
>     * why does the loglcal, pgl_global_ext, even exists, it's true only when evp_algoerithm='shared_mem_1d'.  Why aren't we just using that check and get rid of pgl_global_ext.

We can use that check I agree.

This was introduced as a bug fix in the old evp 1d as HTE and HTN uses their neigbour points  as oppose to the other grid variables. When scattering where the neighbour block is masked out the will provide NaNs or zeros in the global domain. I cant remember which ones - both are wrong and will lead to   wrong results.

That is the reason why this was made just after the variables were read in ice_grid and not in within the dynamic reader initialization..

>     * there is a subroutine in ice_boundary called "primary_grid_lengths_global_ext".  That subroutine has no MPI in it, it should not be in ice_boundary (the mpi and serial version are identical).  That subroutine should probably be in ice_grid.F90.  That also keeps the "pgl" stuff more local.

I think that it is put there as it was made as part of the boundary updates. It can be moved to ice_grid.F90

>     * G_HTE and G_HTN only need to be defined on the master_task and they are global arrays and persistent.  But they are only needed for the evp1d initialization.

Yes
>       
>       * Why can't G_HTE and G_HTN be allocated and initialized in dyn_evp1d_init like G_dxT, G_dyT, G_uarear, and G_tmask?
>       * Why aren't all these global arrays deallocated at the end of dyn_evp1d_init?  Maybe the subroutine does it automatically, but I don't think we can count on it and it would be better to be explicit.

See explanation above with regards to why.
A de allocation can be put on
> 
>
> Anyway, I think you should consider the following implementation
> 
>     * get rid of pgl_global_ext


> 
>     * move G_HTE and G_HTN into dyn_evp1d_init (like G_dxT, G_dyT, G_uarear, and G_tmask) as local variables.  Those would be computed by gathering HTE and HTN then calling primary_grid_lengths_global_ext (which now lives in ice_dyn_evp1d).  Or could G_HTE and G_HTN be added to "global_static" and initialized with a call to gather_global_ext?  That would be even better!  That would get rid of primary_grid_lengths_global_ext completely.
> 
>     * deallocate all those global arrays at the end of dyn_evp1d_init (if you're clever, you can allocate those arrays to size "1" on non root tasks if you want.  they have to be allocated temporarily, but they are never used).
> 
> 
> That would clean up the implementation quite a bit (get rid of pgl_global_ext, localize all logic associated with G_HTE and G_HTN to dyn_evp1d_init, maybe get rid of primary_grid_lengths_global_ext, and reduce memory overall) and should fix the current problem. Hopefully that makes sense, maybe I'm missing something. If you want some help, let me know.

To summarize
I can change/remove pgl_global_ext and name it shared_mem 
I cannot move allocation of G_HTE and G_HTN. 
What I can do allocate full arrays on master and dummy arrays of size (1,1) on all other as they are never used
 
I can add deallocation

2023-11-08 10:16 UTC, TillRasmussen commented
I implemented the changes and realized why the pgl_global_ext was included. If ice_grid has a use ice_dyn_shared statetment then there will be circular dependencies as ice_dyn_shared has a use ice_grid statement

2023-11-08 16:21 UTC, apcraig commented
I'm curious about the issue with G_HTE and G_HTN and why the neighbors need to be valid globally.  The 2d evp implementation uses HTE and HTN to compute cxp/cyp/cxm/cym just fine from the masked fields.  I think the 1d stencil should be identical, so am not sure why G_HTE and G_HTN needs some of those masked values in 1d while in 2d that is not the case.  I assume this problem arises in the computation of the tmp_cxp/cyp/cxm/cym?  Is the problem that 0s or Nans in evp1d lead to a computational issues even though they don't impact the science.  In other words, is the 2d implementation masking computations that don't need to be done and avoiding those 0s/Nans while the 1d is not?  It would be really nice to figure out if there is another way to handle this so G_HTE and G_HTN could just be set in evp1d.  Also, the gather_global_ext implementation allows for user defined "spval" so we could set that to 1.0 or something to override the missing values if it's just a technical issue?

2023-11-08 18:05 UTC, TillRasmussen commented
This was added #568.
Commit on 1st of March 2021

At this time subroutine primary_grid_lengths_global_ext was moved from ice_grid to ice_boundary 13th of March based on a comment from @eclare108213 on the 5th of March.

2023-11-08 21:10 UTC, apcraig commented
I did a bunch of testing on the G_HTE, G_HTN implementation.  I was able to confirm that gathering HTE and HTN in the evp1d results in different answers and sometimes aborts.  Again, I ran many different cases.  I do not understand why this is the case.  I think I'd have to do detailed debugging on a grid point by grid point, line by line basis to understand what's going on.  I did compare G_HTE/G_HTN and a gathered and extended HTE/HTN and the only differences are where blocks are missing.  I also tested a case where NO blocks were eliminated (distribution_wght = 'blockall'), and gathering HTE/HTN works fine.  So it is about land block elimination.

HTE/HTN are used in the evp1d to compute the metrics cxp, cyp, cxm, cym, dxhy, dyhx.  Those metrics are computed in ice_grid from the decomposed HTE and HTN and that computation is duplicated in evp1d.  Obviously, there is a difference in the computation of those metrics on the halos, again, not sure what it is.

What did work in the evp1d is gathering cxp, cyp, cxm, cym, dxhy, dyhx and using those arrays directly (like is done with dxt, dyt, tmask, uarea).  Doing so means HTE and HTN will no longer be used in evp1d and everything can be localized in evp1d.  We can get rid of pgl_global_ext, localize all logic associated with the global grid metrics to dyn_evp1d_init, get rid of primary_grid_lengths_global_ext, and reduce memory overall.  I think this is the way to go at this point.

Finally, I ran the decomp_suite with evp1d with the original implementation (G_HTE, G_HTN) and my proposed implementation (cxp, cyp, cxm, cym, dxhy, dyhx) and the results between the two were identical.  In addition, the decomp_suite fully passed which means the evp1d implementation is bit-for-bit with difference decompositions, block sizes, debug and optimized, etc.  This is good and a requirement.  Finally, I did get bit-for-bit with the evp1d and the 2d for a case with reduced (debug) optimization.  I didn't run a full suite of 1d vs 2d tests.  It could be that 1d and 2d are bit-for-bit with optimized compilation for some machines/compilers and that debug is not, not sure.  I don't think we're requiring evp1d to be bit-for-bit with 2d, it's just a lot easier to test if it is for at least some set of configurations, machines, compilers, and compiler options.

Anyway, my proposal would be to move away from using HTE and HTN in evp1d and use cxp, cyp, cxm, cym, dxhy, dyhx instead.  Those six grid arrays can be handled just like dxt, dyt, tmask, and uarea in the evp1d which would result in some nice cleanup.  If you'd like me to PR something to the branch, so you can test and review, let me know.  I could put that together fairly quickly.  Also happy for @TillRasmussen to do that.  Thanks.

2023-11-08 22:17 UTC, TillRasmussen commented
I would like to keep the structure

The issue is that if I have a variable A with a masked block AA.
And B = gather(scatter(A))
Then B and A is different for the area of AA.
This is not normally a problem as gather are only used for output (diagnostic or dump to files). In these cases one would set a dummy value for area AA.

The problem occurs when for instance G_HTE(i - 1, j) is used. In the traditional evp2d is calculated then i-1 is updated from A have real values. However when this is gathered the halo's are not used and the value used as i-1 will have a dummy value.

Does this help?

2023-11-08 22:34 UTC, TillRasmussen commented
An alternative is to change the gather rutine in order to make an option
that use the halo in order to fill marked arrays. Do we know which block
are neighbours?

ons. 8. nov. 2023 19.10 skrev Tony Craig ***@***.***>:

> I did a bunch of testing on the G_HTE, G_HTN implementation. I was able to
> confirm that gathering HTE and HTN in the evp1d results in different
> answers and sometimes aborts. Again, I ran many different cases. I do not
> understand why this is the case. I think I'd have to do detailed debugging
> on a grid point by grid point, line by line basis to understand what's
> going on. I did compare G_HTE/G_HTN and a gathered and extended HTE/HTN and
> the only differences are where blocks are missing. I also tested a case
> where NO blocks were eliminated (distribution_wght = 'blockall'), and
> gathering HTE/HTN works fine. So it is about land block elimination.
>
> HTE/HTN are used in the evp1d to compute the metrics cxp, cyp, cxm, cym,
> dxhy, dyhx. Those metrics are computed in ice_grid from the decomposed HTE
> and HTN and that computation is duplicated in evp1d. Obviously, there is a
> difference in the computation of those metrics on the halos, again, not
> sure what it is.
>
> What did work in the evp1d is gathering cxp, cyp, cxm, cym, dxhy, dyhx and
> using those arrays directly (like is done with dxt, dyt, tmask, uarea).
> Doing so means HTE and HTN will no longer be used in evp1d and everything
> can be localized in evp1d. We can get rid of pgl_global_ext, localize all
> logic associated with the global grid metrics to dyn_evp1d_init, get rid of
> primary_grid_lengths_global_ext, and reduce memory overall. I think this is
> the way to go at this point.
>
> Finally, I ran the decomp_suite with evp1d with the original
> implementation (G_HTE, G_HTN) and my proposed implementation (cxp, cyp,
> cxm, cym, dxhy, dyhx) and the results between the two were identical. In
> addition, the decomp_suite fully passed which means the evp1d
> implementation is bit-for-bit with difference decompositions, block sizes,
> debug and optimized, etc. This is good and a requirement. Finally, I did
> get bit-for-bit with the evp1d and the 2d for a case with reduced (debug)
> optimization. I didn't run a full suite of 1d vs 2d tests. It could be that
> 1d and 2d are bit-for-bit with optimized compilation for some
> machines/compilers and that debug is not, not sure. I don't think we're
> requiring evp1d to be bit-for-bit with 2d, it's just a lot easier to test
> if it is for at least some set of configurations, machines, compilers, and
> compiler options.
>
> Anyway, my proposal would be to move away from using HTE and HTN in evp1d
> and use cxp, cyp, cxm, cym, dxhy, dyhx instead. Those six grid arrays can
> be handled just like dxt, dyt, tmask, and uarea in the evp1d which would
> result in some nice cleanup. If you'd like me to PR something to the
> branch, so you can test and review, let me know. I could put that together
> fairly quickly. Also happy for @TillRasmussen
> <https://github.com/TillRasmussen> to do that. Thanks.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CICE-Consortium/CICE/pull/895#issuecomment-1802686399>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH7N7DUBIIBI2CH2M25DZFLYDPYNJAVCNFSM6AAAAAA6OK6NFWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBSGY4DMMZZHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-08 23:08 UTC, apcraig commented
> I would like to keep the structure as it increases performance. We can talk about it tomorrow that might be easier.
> 
> The issue is that if I have a variable A with a masked block AA. And B = gather(scatter(A)) Then B and A is different for the area of AA. This is not normally a problem as gather are only used for output (diagnostic or dump to files). In these cases one would set a dummy value for area AA.
> 
> The problem occurs when for instance G_HTE(i - 1, j) is used. In the traditional evp2d is calculated then i-1 is updated from A have real values. However when this is gathered the halo's are not used and the value used as i-1 will have a dummy value.
> 
> Does this help?

OK, I looked again. You are right that HTE and HTN are scattered from the global arrays.  So they are not created from a field that has the blocks eliminated.  I missed that.  That explains why gather(HTE) doesn't work quite the same as G_HTE.  OK, it's a little worrisome that some of the grid metrics depend on neighbor info that might not be there (as we see from the evp1d implementation)!  But that's a separate issue.

I still favor using cxp, cyp, cxm, cym, dxhy, dyhx instead of G_HTE and G_HTN.  The code is much cleaner and I really don't believe there will be a performance penalty.  The main difference is that we gather those 6 arrays ONCE during the evp1d initialization and then store them (like dxt, dyt, tmask, uarea).  But we also eliminate six mult-add computations in stress_1d (ie. tmp_cxp, those become copies).  Those computations happen every subcycle (even though they can be precomputed as my method does).  The new implementation might even speed up the code.  But my guess is that we won't be able to measure a performance difference in the two approaches.  There seem to be lots of other bigger fish to fry wrt evp1d performance!

The other benefit is that you won't have to maintain the computation of cxp, cyp, cxm, cym, dxhy, dyhx in evp1d if it changes in ice_grid.  You'll get that maintenance for free.  I really don't see any downsides to making this change.  The only issues might be extra memory use (we eliminate 2 global arrays on master but add 6 others == 4MB total increase for gx1) or if it impacts the benchmark testing, but I think that just means you have to pull out the cxp, cyp, cxm, cym, dxhy, dyhx calculation into the benchmark driver, should be easy.

2023-11-08 23:33 UTC, apcraig commented
I just ran a quick timing comparison.  current implementation vs the one I'm proposing.

```
original evp1d:
Timer   1:     Total      66.11 seconds
Timer   2:  TimeLoop      65.75 seconds
Timer   3:  Dynamics      30.48 seconds
Timer   4: Advection       6.22 seconds
Timer   5:    Column      18.02 seconds
Timer   6:    Thermo      15.73 seconds
Timer   7: Shortwave       6.29 seconds
Timer   8:   Ridging       2.29 seconds
Timer   9:  FloeSize       0.00 seconds
Timer  10:  Coupling       4.94 seconds
Timer  11: ReadWrite       1.09 seconds
Timer  12:     Diags       4.97 seconds
Timer  13:   History       0.47 seconds
Timer  14:     Bound      13.71 seconds
Timer  15: Bundbound       0.03 seconds
Timer  16:       BGC       0.00 seconds
Timer  17:   Forcing       1.55 seconds
Timer  18: evp1dcore      26.11 seconds
Timer  19:       evp      30.00 seconds
Timer  20:  UpdState       9.34 seconds


proposed evp1d:
Timer   1:     Total      65.72 seconds
Timer   2:  TimeLoop      65.39 seconds
Timer   3:  Dynamics      29.92 seconds
Timer   4: Advection       6.34 seconds
Timer   5:    Column      18.04 seconds
Timer   6:    Thermo      15.81 seconds
Timer   7: Shortwave       6.34 seconds
Timer   8:   Ridging       2.24 seconds
Timer   9:  FloeSize       0.00 seconds
Timer  10:  Coupling       4.94 seconds
Timer  11: ReadWrite       1.17 seconds
Timer  12:     Diags       4.95 seconds
Timer  13:   History       0.47 seconds
Timer  14:     Bound      13.76 seconds
Timer  15: Bundbound       0.03 seconds
Timer  16:       BGC       0.00 seconds
Timer  17:   Forcing       1.47 seconds
Timer  18: evp1dcore      25.54 seconds
Timer  19:       evp      29.44 seconds
Timer  20:  UpdState       9.40 seconds
```

This is one test, one sample, so I'm not going to suggest it's meaningful.  But the timers are pretty consistent between the two cases except dynamics.  The evp1dcore seems to be 0.5s (2%) faster in the new implementation.  This is for gx3 running on 4x4 pes with 5x29 block size and slenderX2 decomp.

And just for fun, here's the standard 2d evp for the same case, quite a bit slower :)

```
Timer   1:     Total      85.79 seconds
Timer   2:  TimeLoop      85.46 seconds
Timer   3:  Dynamics      50.12 seconds
Timer   4: Advection       6.35 seconds
Timer   5:    Column      18.01 seconds
Timer   6:    Thermo      15.73 seconds
Timer   7: Shortwave       6.35 seconds
Timer   8:   Ridging       2.28 seconds
Timer   9:  FloeSize       0.00 seconds
Timer  10:  Coupling       4.93 seconds
Timer  11: ReadWrite       1.06 seconds
Timer  12:     Diags       4.93 seconds
Timer  13:   History       0.46 seconds
Timer  14:     Bound      45.68 seconds
Timer  15: Bundbound       1.75 seconds
Timer  16:       BGC       0.00 seconds
Timer  17:   Forcing       1.49 seconds
Timer  18: evp1dcore       0.00 seconds
Timer  19:       evp      49.65 seconds
Timer  20:  UpdState       9.38 seconds
```

2023-11-09 01:41 UTC, apcraig commented
I created a PR for my latest proposed changes, so others could see.  I'm testing them comprehensively now.  Not saying we have to do it, just an option.  https://github.com/TillRasmussen/CICE/pull/20

2023-11-11 22:15 UTC, TillRasmussen commented
I have run qc test on all simulation without debug
Old 2d version vs new 2d version bit for bit
Old 2d version vs new 2d version and more aggressive compiler flags pass qc test
Old 2d version vs new 1d version pass qc test
Old 2d version vs new 1d version and aggressive compiler flags. Pass test. Maximum difference is ~-3e-02 according to colorbar. Probably found in the Canadian Arctic

2023-11-16 17:11 UTC, apcraig commented
Full test suites run on cheyenne and derecho (8 compilers), all results look good.  https://github.com/CICE-Consortium/Test-Results/wiki/cice_by_hash_forks#4454216df83760ff49c38f51fe6d5a3f85fe9ad3

I also ran a decomp_suite with -s evp1d and that also passed.  I will merge this later today unless anyone has anything else.

2023-11-16 17:11 UTC, apcraig approved these changes

2023-11-16 21:12 UTC, merged